// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCA.DataAccess.Context;

#nullable disable

namespace TCA.DataAccess.Migrations.CollectiveServiceTestDB
{
    [DbContext(typeof(CollectiveServiceTestDBContext))]
    partial class CollectiveServiceTestDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCA.Entities.Models.HR_Grup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("GrupKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Grup");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Birim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<int?>("BirimKodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Birim");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Bolum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<int?>("BolumKodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Bolum");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Gorev", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("GorevKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Gorev");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_IK_Yetki", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonAnahtari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_IK_Yetki");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_IsAlani", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("IsAlaniKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_IsAlani");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Lokasyon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("LokasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Lokasyon");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_MasrafYeri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("MasrafKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_MasrafYeri");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_MobilUsers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("Sicil")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_MobilUsers");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_OrganizasyonAnahtar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AnahtarKodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("IKSicil")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_OrganizasyonAnahtar");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Personel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirimKodu")
                        .HasColumnType("int");

                    b.Property<string>("BirimTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BolumKodu")
                        .HasColumnType("int");

                    b.Property<string>("BolumTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalisanAltGrup")
                        .HasColumnType("int");

                    b.Property<int?>("CalisanGrubu")
                        .HasColumnType("int");

                    b.Property<string>("CepNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<string>("Dahili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("DurumEba")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DurumPasif")
                        .HasColumnType("datetime2");

                    b.Property<string>("EkOnayci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GorevKodu")
                        .HasColumnType("int");

                    b.Property<string>("GorevTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupKodu")
                        .HasColumnType("int");

                    b.Property<string>("GrupTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAlaniKodu")
                        .HasColumnType("int");

                    b.Property<string>("IsAlaniTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiselMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LokasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("LokasyonTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasrafKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasrafTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Onayci1")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci2")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci3")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci4")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci5")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizasyonAmirSicil")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonAnahtarIK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizasyonAnahtarKodu")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonAnahtarTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonMasterKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizasyonTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAltAlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.Property<string>("SirketGenelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketGenelTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SozlesmeKodu")
                        .HasColumnType("int");

                    b.Property<string>("SozlesmeTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnvanKodu")
                        .HasColumnType("int");

                    b.Property<string>("UnvanTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZzMailBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hr_sap_manuel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_Personel");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Personel_Taseron", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirimKodu")
                        .HasColumnType("int");

                    b.Property<string>("BirimTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BolumKodu")
                        .HasColumnType("int");

                    b.Property<string>("BolumTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CalisanAltGrup")
                        .HasColumnType("int");

                    b.Property<int?>("CalisanGrubu")
                        .HasColumnType("int");

                    b.Property<string>("CepNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<string>("Dahili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DurumPasif")
                        .HasColumnType("datetime2");

                    b.Property<string>("EkOnayci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GorevKodu")
                        .HasColumnType("int");

                    b.Property<string>("GorevTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupKodu")
                        .HasColumnType("int");

                    b.Property<string>("GrupTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAlaniKodu")
                        .HasColumnType("int");

                    b.Property<string>("IsAlaniTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiselMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LokasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("LokasyonTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasrafKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasrafTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Onayci1")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci2")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci3")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci4")
                        .HasColumnType("int");

                    b.Property<int?>("Onayci5")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizasyonAmirSicil")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonAnahtarIK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizasyonAnahtarKodu")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonAnahtarTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("OrganizasyonMasterKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizasyonTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAltAlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.Property<string>("SirketGenelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketGenelTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SozlesmeKodu")
                        .HasColumnType("int");

                    b.Property<string>("SozlesmeTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnvanKodu")
                        .HasColumnType("int");

                    b.Property<string>("UnvanTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZzMailBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hr_sap_manuel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_Personel_Taseron");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Seviye", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ALTHIZMET_TURU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("HIZMET_TURU")
                        .HasColumnType("int");

                    b.Property<string>("MASRAF_YERI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONAYCI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORGTX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POZISYON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEVIYE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEVIYE_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIRKET_KODU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNVAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UP_OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Seviye");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Sirketler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Sirketler");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Sozlesme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("SozlesmeKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Sozlesme");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Models.HR_Unvan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnvanKodu")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HR_Unvan");
                });

            modelBuilder.Entity("TCA.Entities.Models.HR_Organizasyon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("APIStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserID")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizasyonKodu")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HR_Organizasyon");
                });
#pragma warning restore 612, 618
        }
    }
}
